- name: install neutron packages
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - openstack-neutron
    - openstack-neutron-linuxbridge
    - ebtables
    - ipset
    - openstack-neutron-ml2
  register: install_result
  until: install_result is success
  retries: 5
  delay: 2

- name: Display installation information
  debug: 
    msg: "Package installed: {{ install_result }}"