- name: sync nova-api database
  command: su -s /bin/sh -c "nova-manage api_db sync" nova

- name: register cell0 database
  command: su -s /bin/sh -c "nova-manage cell_v2 map_cell0" nova

- name: create cell1 cell
  command: su -s /bin/sh -c "nova-manage cell_v2 create_cell --name=cell1 --verbose" nova

- name: sync nova database
  command: su -s /bin/sh -c "nova-manage db sync" nova 

- name: validate cell0 and cell1 register if right
  command: su -s /bin/sh -c "nova-manage cell_v2 list_cells" nova

- name: add computer node to openstack cluster
  command: su -s /bin/sh -c "nova-manage cell_v2 discover_hosts --verbose" nova 
    