# 渲染neutron.conf文件
- name: render /etc/neutron/neutron.conf file 
  template:
    src: ../templates/neutron.conf.j2
    dest: /etc/neutron/neutron.conf

# upload ml2_conf.ini by template
- name: upload ml2_conf.ini file to remote
  copy:
    src: ../templates/ml2_conf.ini
    dest: /etc/neutron/plugins/ml2/ml2_conf.ini
  register: upload_result
  failed_when: upload_result.failed  # 上传失败时报错

# 判断ml2源文件是否存在
- name: check /etc/neutron/plugins/ml2/ml2_conf.ini if existence
  stat:
    path: /etc/neutron/plugins/ml2/ml2_conf.ini
  register: ml2file_info

# 符号连接是否存在
- name: check /etc/neutron/plugin.ini
  stat:
    path: /etc/neutron/plugin.ini
  register: plugin_info

# 当符号链接不存在且源文件存在时，为/etc/neutron/plugins/ml2/ml2_conf.ini文件建立软连接
- name: create soft link
  command: ln -s /etc/neutron/plugins/ml2/ml2_conf.ini /etc/neutron/plugin.ini
  when: not plugin_info.stat.exists and ml2file_info.stat.exists 

# 获取远程节点的网络接口信息
- name: Get interface name
  setup:
  register: setup_interface_result

# 渲染 /etc/neutron/linuxbridge_agent.ini 文件
- name: render linuxbridge_agent.ini file
  template:
    src: ../templates/linuxbridge_agent.ini.j2
    dest: /etc/neutron/plugins/ml2/linuxbridge_agent.ini
  vars:
    PROVIDER_INTERFACE_NAME: "{{ setup_interface_result.ansible_facts['ansible_interfaces'][0] }}"  # 将第一个接口渲染到linuxbridge_agent.ini文件
    # COMPUTER_IP: "{{ COMPUTER_IP }}"     #############这里需要修改为当前节点的ip

    