- name: install openstack-cinder-api & openstack-cinder-scheduler
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - openstack-cinder-api
    - openstack-cinder-scheduler
  register: install_result
  until: install_result is success
  retries: 5
  delay: 2

  
- name: display install cinder result info
  debug:
    msg: "install res: {{ install_result }}"