- name: create database cinder
  mysql_db:
    login_user: root
    login_password: "{{ MYSQL_DBPASS }}"
    login_unix_socket: /var/lib/mysql/mysql.sock   # 指定mariadb的unix socket 路径
    name: cinder
    state: present

# start grant database for cinder
- name: Grant privileges to cinder database user (localhost)
  mysql_user:
    # login_user: root
    # login_password: 
    login_unix_socket: /var/lib/mysql/mysql.sock   # 指定mariadb的unix socket 路径
    name: cinder
    password: "{{ CINDER_DBPASS }}"
    host: localhost
    priv: "cinder.*:ALL"
    state: present

- name: Grant privileges to cinder database user (%)
  mysql_user:
    # login_user: root
    # login_password: "{{ mysql_root_password }}"
    login_unix_socket: /var/lib/mysql/mysql.sock   # 指定mariadb的unix socket 路径
    name: cinder
    password: "{{ CINDER_DBPASS }}"
    host: "%"
    priv: "cinder.*:ALL"
    state: present