
- name: Install MariaDB packages including (mariabd,mariabd-server,python3-PyMySQL)
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - mariadb
    - mariadb-server
    - python3-PyMySQL
  register: install_result
  until: install_result is success
  retries: 5
  delay: 2


- name: Display installation information
  debug: 
    msg: "Package installed: {{ install_result }}"

  # - name: Create mariadb log dir
  #   file:
  #     path: "/var/log/mariadb"
  #     state: "directory"
  #     group: "mysql"
  #     owner: "mysql"
  #     mode: "0755"


