- name: Install rabbitmq packages including rabbitmq-server only
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - rabbitmq-server
  register: install_result
  until: install_result is success
  retries: 5
  delay: 2

- name: Display installation information
  debug: 
    msg: "Package installed: {{ install_result }}"

