- name: login mariadb and create glance database
  mysql_db:
    login_user: root
    login_password: "{{ MYSQL_DBPASS }}"
    login_unix_socket: /var/lib/mysql/mysql.sock   # 指定mariadb的unix socket 路径
    name: glance
    state: present

- name: Grant privileges to glance database user (localhost)
  mysql_user:
    # login_user: root
    # login_password: 
    login_unix_socket: /var/lib/mysql/mysql.sock   # 指定mariadb的unix socket 路径
    name: glance
    password: "{{ GLANCE_DBPASS }}"
    host: localhost
    priv: "glance.*:ALL"
    state: present

- name: Grant privileges to glance database user (%)
  mysql_user:
    # login_user: root
    # login_password: "{{ mysql_root_password }}"
    login_unix_socket: /var/lib/mysql/mysql.sock   # 指定mariadb的unix socket 路径
    name: glance
    password: "{{ GLANCE_DBPASS }}"
    host: "%"
    priv: "glance.*:ALL"
    state: present

