- name: login mariadb and create keystone database
  mysql_db:
    login_user: root
    login_password: "{{ MYSQL_DBPASS }}"
    login_unix_socket: /var/lib/mysql/mysql.sock   # 指定mariadb的unix socket 路径
    name: keystone
    state: present

- name: Grant privileges to Keystone database user (localhost)
  mysql_user:
    # login_user: root
    # login_password: 
    login_unix_socket: /var/lib/mysql/mysql.sock   # 指定mariadb的unix socket 路径
    name: keystone
    password: "{{ KEYSTONE_DBPASS }}"
    host: localhost
    priv: "keystone.*:ALL"
    state: present

- name: Grant privileges to Keystone database user (%)
  mysql_user:
    # login_user: root
    # login_password: "{{ mysql_root_password }}"
    login_unix_socket: /var/lib/mysql/mysql.sock   # 指定mariadb的unix socket 路径
    name: keystone
    password: "{{ KEYSTONE_DBPASS }}"
    host: "%"
    priv: "keystone.*:ALL"
    state: present

