- name: Install keystone packages including (openstack-keystone,httpd,mod_wsgi)
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - openstack-keystone 
    - httpd 
    - mod_wsgi
  register: install_result
  until: install_result is success
  retries: 5
  delay: 2

- name: Display installation information
  debug: 
    msg: "Package installed: {{ install_result }}"