- name: login mariadb and create placement database
  mysql_db:
    login_user: root
    login_password: "{{ MYSQL_DBPASS }}"
    login_unix_socket: /var/lib/mysql/mysql.sock   # 指定mariadb的unix socket 路径
    name: placement
    state: present

- name: Grant privileges to placement database user (localhost)
  mysql_user:
    # login_user: root
    # login_password: 
    login_unix_socket: /var/lib/mysql/mysql.sock   # 指定mariadb的unix socket 路径
    name: placement
    password: "{{ PLACEMENT_DBPASS }}"
    host: localhost
    priv: "placement.*:ALL"
    state: present

- name: Grant privileges to placement database user (%)
  mysql_user:
    # login_user: root
    # login_password: "{{ mysql_root_password }}"
    login_unix_socket: /var/lib/mysql/mysql.sock   # 指定mariadb的unix socket 路径
    name: placement
    password: "{{ PLACEMENT_DBPASS }}"
    host: "%"
    priv: "placement.*:ALL"
    state: present

