- name: install openstack-placement-api including openstack-placement-api only
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - openstack-placement-api
  register: install_result
  until: install_result is success
  retries: 5
  delay: 2

- name: Display installation information
  debug: 
    msg: "Package installed: {{ install_result }}"
        